### ISSUE TITLE
歌曲列表切换会重复加1行

### ISSUE THREAD

**Issue by dql2583185057** [xyyfun/music#2]
在歌曲列表，点击评论再切回歌曲会数据会重复加1遍
![8(` BT}FZ2(30QPK XJSE2](https://github.com/xyyfun/music/assets/39696527/34b1e1ca-1b07-4e80-a077-f455f65738d5)
![6$ 68Z1 A3H2 F0T T9W7P6](https://github.com/xyyfun/music/assets/39696527/9f67231c-3653-4bac-bd87-c248c164fc15)

**Comment by xyyfun** [comment]
@dql2583185057 问题已修复请拉取最新代码
